# Write a program to create a clock

import time
import os
import sys
import datetime

while True:
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    os.system("cls")
    print("The time is:",datetime.datetime.now())
    time.sleep(1)
    sys.stdout.flush()
    